### ISSUE TITLE
Backup scraper failed...

### ISSUE THREAD

**Issue by IllNoobis** [1f1n/Dragon#11]
A lot of errors...

' Backup scraper failed, retrying...
[🐲] Error fetching data, trying backup...
[🐲] Error fetching data, trying backup...
[🐲] Backup scraper failed, retrying...

[🐲] Missing 'wallet' key in result: {'totalProfitPercent': '-1.44%', '7dUSDProfit': '$-1,032.36', '30dUSDProfit': '$-1,032.36', 'winrate_7d': '?', 'winrate_30d': '?', 'tags': [], 'sol_balance': '0.00', 'token_distribution': {'No Token Distribution Data': None}, 'directLink': 'https://gmgn.ai/sol/address/91dLmoBspJUGswDiMJnuoVSLWwAw8yY9yVaLnAbiZTqy', 'buy_7d': '1635'}
[🐲] File choice out of range.'

I removed a load of them as well, it worked once then it stoped working...

**Comment by IllNoobis** [comment]
![image](https://github.com/user-attachments/assets/37d8c4e8-ba4f-4f5d-8ba8-f5362067ca7c)

**Comment by 1f1n** [comment]
I suggest using proxies or a fresh IP that hasn't been limited by Cloudflare before.
