### ISSUE TITLE
[🐲] Backup scraper failed, retrying...

### ISSUE THREAD

**Issue by fb0x** [1f1n/Dragon#12]
I keep getting this error with get Get Transaction By Timestamp method. I have new ips and other methods i tried seems to be working fine but this except this one. I did lower the range but still this keeps happening any idea why?

**Comment by 1f1n** [comment]
It's normal, as long as the file doesn't crash / return 0 wallets then it's running. Just leave it to run until it's finished.

**Comment by fb0x** [comment]
it works but the file is always empty any idea why?

**Comment by fb0x** [comment]
also it seems to be working with some pairs and not with some others. Do you think it happens because dataset is too large?

**Comment by 1f1n** [comment]
> it works but the file is always empty any idea why?

Means GMGN returned no JSON data for each request which likely means your IP is ratelimited, try proxies or a fresh IP/VPS/VPN.
