### ISSUE TITLE
All Transaction Scan - not working

### ISSUE THREAD

**Issue by josetommaso** [1f1n/Dragon#17]
I've tried the All Transaction Scan option but it returns a 403 error.

![image](https://github.com/user-attachments/assets/e26010a5-0dc1-4407-9bc6-ff2142ddfc20)

thanks :)

**Comment by 1f1n** [comment]
A [403 error](https://http.cat/403) is a response error from the API response (https://gmgn.ai).

My suggestion is to keep retrying, get your IP whitelisted to their API or read [this](https://github.com/1f1n/Dragon/blob/main/README.md#note).
