### ISSUE TITLE
How to fetch tokens

### ISSUE THREAD

**Issue by roguetitan1703** [1f1n/Dragon#18]
Maybe not exactly an issue but, I was wondering that how to populate the tokens.txt because without a organic and accurate list of tokens, it would be of no use.
if we can discuss this it would be great

**Comment by Sky98040** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by 1f1n** [comment]
Use the GMGN tools section.
