### ISSUE TITLE
Dragon.py doesn't work

### ISSUE THREAD

**Issue by TilekT** [1f1n/Dragon#3]
Hi,
tried to use the program several times 
gives errors

] Please select a chain:

[1] Solana
[2] Tron
[3] Ethereum

[❓] Choice > 1
[🐲] Selected Solana
[🐲] Please select a module:

[1] Bundle Checker
[2] Bulk Wallet Checker
[3] Top Traders Scraper
[4] All Transaction Scan
[5] Get Transaction By Timestamp
[6] Copy Wallet Finder
[7] Top Holders Scraper
[8] Purge All Files
[9] Quit

[❓] Choice > 7
[🐲] Selected Top Holders Scraper
[❓] Threads > 5
[❓] Use Proxies? (Y/N) > n
[🐲] Loaded 1 contract addresses
[🐲] Backup scraper failed, retrying... HTTPSConnectionPool(host='gmgn.ai', port=443): Max retries exceeded with url: /defi/quotation/v1/tokens/top_holders/sol/?orderby=amount_percentage&direction=desc (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1020)')))
[🐲] Backup scraper failed, retrying... HTTPSConnectionPool(host='gmgn.ai', port=443): Max retries exceeded with url: /defi/quotation/v1/tokens/top_holders/sol/?orderby=amount_percentage&direction=desc (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1020)')))
[🐲] Backup scraper failed, retrying... HTTPSConnectionPool(host='gmgn.ai', port=443): Max retries exceeded with url: /defi/quotation/v1/tokens/top_holders/sol/?orderby=amount_percentage&direction=desc (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1020)')))
[🐲] Failed to fetch data after 3 attempts.
[🐲] Error fetching data on attempt, trying backup HTTPSConnectionPool(host='gmgn.ai', port=443): Max retries exceeded with url: /defi/quotation/v1/tokens/sol/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1020)')))
Traceback (most recent call last):
  File "/Users/tilektoi/Desktop/dev/analyzer/Dragon/dragon.py", line 825, in <module>
    solana()
    ~~~~~~^^
  File "/Users/tilektoi/Desktop/dev/analyzer/Dragon/dragon.py", line 788, in solana
    data = topHolders.topHolderData(contractAddresses, threads, useProxies)
  File "/Users/tilektoi/Desktop/dev/analyzer/Dragon/Dragon/holders.py", line 213, in topHolderData
    identifier = self.shorten(list(self.allAddresses)[0])
                              ~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by 1f1n** [comment]
I've added User Agent randomisation & TLS handshake client session randomisation too, you'll still get failed requests but for the most part it'll work.
