### ISSUE TITLE
I need your Help, the dragon doesn't work

### ISSUE THREAD

**Issue by lemonarque237** [1f1n/Dragon#4]
Hi,
i need your help please, tried to use the program several times
 and it doesent work well..I guess

[🐲] Please select a chain:

[1] Solana
[2] Tron
[3] Ethereum

[❓] Choice > 1
[🐲] Selected Solana
[🐲] Please select a module:

[1] Bundle Checker
[2] Bulk Wallet Checker
[3] Top Traders Scraper
[4] All Transaction Scan
[5] Get Transaction By Timestamp
[6] Copy Wallet Finder
[7] Top Holders Scraper
[8] Purge All Files
[9] Quit

[❓] Choice > 2
[🐲] Selected Bulk Wallet Checker

[1] BulkWallet/wallets.txt
[2] TopHolders/tokens.txt
[3] Select Own File

[❓] File Choice > 1
[🐲] Selected BulkWallet/wallets.txt
[🐲] Error occurred, file may be empty.
[❓] File Choice > 1
[🐲] Selected BulkWallet/wallets.txt
[🐲] Error occurred, file may be empty.
[❓] File Choice > 1
[🐲] Selected BulkWallet/wallets.txt
[🐲] Error occurred, file may be empty.
[❓] File Choice > 1
[🐲] Selected BulkWallet/wallets.txt
[🐲] Error occurred, file may be empty.
[❓] File Choice > 1
[🐲] Selected BulkWallet/wallets.txt
[🐲] Error occurred, file may be empty.
[❓] File Choice > 1
[🐲] Selected BulkWallet/wallets.txt
[🐲] Error occurred, file may be empty.
[❓] File Choice > 1
[🐲] Selected BulkWallet/wallets.txt
[🐲] Error occurred, file may be empty.
[❓] File Choice > 2
[🐲] Selected TopHolders/tokens.txt
[🐲] Error occurred, file may be empty.
[❓] File Choice >

and it goes on for every choise. I cant even go back, I have to start the program everytime from beguin to try again

**Comment by Tao546127REP** [comment]
> Hi, i need your help please, tried to use the program several times and it doesent work well..I guess
> 
> [🐲] Please select a chain:
> 
> [1] Solana [2] Tron [3] Ethereum
> 
> [❓] Choice > 1 [🐲] Selected Solana [🐲] Please select a module:
> 
> [1] Bundle Checker [2] Bulk Wallet Checker [3] Top Traders Scraper [4] All Transaction Scan [5] Get Transaction By Timestamp [6] Copy Wallet Finder [7] Top Holders Scraper [8] Purge All Files [9] Quit
> 
> [❓] Choice > 2 [🐲] Selected Bulk Wallet Checker
> 
> [1] BulkWallet/wallets.txt [2] TopHolders/tokens.txt [3] Select Own File
> 
> [❓] File Choice > 1 [🐲] Selected BulkWallet/wallets.txt [🐲] Error occurred, file may be empty. [❓] File Choice > 1 [🐲] Selected BulkWallet/wallets.txt [🐲] Error occurred, file may be empty. [❓] File Choice > 1 [🐲] Selected BulkWallet/wallets.txt [🐲] Error occurred, file may be empty. [❓] File Choice > 1 [🐲] Selected BulkWallet/wallets.txt [🐲] Error occurred, file may be empty. [❓] File Choice > 1 [🐲] Selected BulkWallet/wallets.txt [🐲] Error occurred, file may be empty. [❓] File Choice > 1 [🐲] Selected BulkWallet/wallets.txt [🐲] Error occurred, file may be empty. [❓] File Choice > 1 [🐲] Selected BulkWallet/wallets.txt [🐲] Error occurred, file may be empty. [❓] File Choice > 2 [🐲] Selected TopHolders/tokens.txt [🐲] Error occurred, file may be empty. [❓] File Choice >
> 
> and it goes on for every choise. I cant even go back, I have to start the program everytime from beguin to try again



Hey there @lemonarque237  It seems like you're having some trouble with the Bulk Wallet Checker on Solana. The error message indicates that the file may be empty. Have you checked the content of the "wallets.txt" file to ensure it's not empty or missing any necessary information? Double-checking the file content might help resolve the issue you're facing. Let me know if you need further assistance!

**Comment by davd-ops** [comment]
Hi, you just need to put the addresses you want to target into those files (wallets.txt or tokens.txt). The path where to put the addresses is `Dragon>data>Solana>BulkWallet`
