### ISSUE TITLE
Cloudflare is blocking all requests

### ISSUE THREAD

**Issue by davd-ops** [1f1n/Dragon#6]
Gmgn added some new cloudflare protection and it is now not possible to query their website from this code

**Comment by davd-ops** [comment]
@1f1n cc

**Comment by Senaxx** [comment]
it seems they added cloudflare advanced protection.

**Comment by 1f1n** [comment]
I've added User Agent randomisation & TLS handshake client session randomisation too, you'll still get failed requests but for the most part it'll work.
