### ISSUE TITLE
No module named 'Dragon.tronTraders'

### ISSUE THREAD

**Issue by LZING** [1f1n/Dragon#7]
![image](https://github.com/user-attachments/assets/39a4c8be-8bf4-496c-b975-4b47524f488e)

The following packages cannot be found, please help me fix them！ Thx

**Comment by LZING** [comment]
I have solved the problem and just deleted it. Thanks

**Comment by 1f1n** [comment]
Yeah sorry I forgot to delete those lines when I deprecated Tron, my bad. Glad you fixed it yourself.
