### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by shali1995** [1f1n/Dragon#8]
X@192 Dragon-main % python3 dragon.py
Traceback (most recent call last):
  File "/Users/shalva/Downloads/Dragon-main/dragon.py", line 1, in <module>
    from Dragon import utils, BundleFinder, ScanAllTx, BulkWalletChecker, TopTraders, TimestampTransactions, purgeFiles, CopyTradeWalletFinder, TopHolders, EarlyBuyers, checkProxyFile
  File "/Users/shalva/Downloads/Dragon-main/Dragon/__init__.py", line 10, in <module>
    from Dragon.tronTraders import TronTopTraders
ModuleNotFoundError: No module named 'Dragon.tronTraders'

cant run it.

**Comment by 1f1n** [comment]
Yeah sorry it was late when I deprecated Tron, you can either delete the lines in [here](https://github.com/1f1n/Dragon/blob/main/Dragon/__init__.py) related to Tron or just reclone the repository.
