### ISSUE TITLE
are proxies necessary to get buyer wallets for a coin?

### ISSUE THREAD

**Issue by fb0x** [1f1n/Dragon#9]
for some reason I'm not able to see with no proxies but when i try to see the url on browser it works. Any idea why this happens?

**Comment by Annawoody** [comment]
@fb0x Sometimes, proxies can interfere with how certain URLs are accessed. If it works on your browser without any proxies, it might be a network configuration issue or something related to the proxy settings themselves.

**Comment by 1f1n** [comment]
Not sure how this is related to my tool.
